services:
  frontend:
    # Use the frontend Docker image tagged with 'test-prod'
    image: front-a-deux-pas:test-prod
    # Connect the frontend container to the 'front-back-network' to enable communication with the backend service
    networks:
      - front-back-network
    # Map port 80 inside the container to port 1080 on the host machine
    ports:
      - "80:1080"
    # Linking the frontend to the backend service
    depends_on:
      - backend
    # Automatically restarting the service if it fails
    restart: always

  backend:
    # Use the backend Docker image tagged with 'test-prod'
    image: back-a-deux-pas:test-prod
    # Connect the backend container to the 'front-back-network' to enable communication with the frontend service
    networks:
      - front-back-network
    # Map port 8081 inside the container to port 9003 on the host machine
    ports:
      - "9003:8081"
    # Automatically restarting the service if it fails
    restart: always
# Define the custom network 'front-back-network' for communication between frontend and backend services
networks:
  front-back-network:
