name: Deploy to EC2

on:
  push:
    branches:
      - main
      - feature/deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Créer le répertoire .ssh si nécessaire
          mkdir -p ~/.ssh

          # Ajouter la clé de l'hôte au fichier known_hosts
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          # Créer la clé privée
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

          # Copier les fichiers nécessaires sur l'instance EC2
          scp -i private_key -r front-a-deux-pas back-a-deux-pas docker-compose.yml ${USER}@${HOST}:~/app

          # Se connecter à l'instance EC2
          ssh -i private_key ${USER}@${HOST} '
            cd ~/app
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            sudo docker-compose pull
            sudo docker-compose up -d --no-deps --build
            docker logout
          '
