name: Deploy to EC2

# on:
#   workflow_dispatch:
#   repository_dispatch:
#     types: [new-release]

on:
  push:
    branches:
      - feature/deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the app latest versions
        id: versions
        run: |
          FRONT_VERSION=$(curl -s https://api.github.com/repos/a-deux-pas/front-a-deux-pas/releases/latest | jq -r '.tag_name | select(startswith("v"))')
          BACK_VERSION=$(curl -s https://api.github.com/repos/a-deux-pas/back-a-deux-pas/releases/latest | jq -r '.tag_name | select(startswith("v"))')
          echo "FRONT_VERSION=${FRONT_VERSION#v}" >> $GITHUB_OUTPUT
          echo "BACK_VERSION=${BACK_VERSION#v}" >> $GITHUB_OUTPUT
        # run: |
        #   if [[ "${{ github.event.client_payload.app }}" == "front-end" ]]; then
        #     echo "FRONT_VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT
        #     BACK_VERSION=$(curl -s https://api.github.com/repos/a-deux-pas/back-a-deux-pas/releases/latest | jq -r '.tag_name | select(startswith("v"))')
        #     echo "BACK_VERSION=${BACK_VERSION#v}" >> $GITHUB_OUTPUT
        #   else
        #     FRONT_VERSION=$(curl -s https://api.github.com/repos/a-deux-pas/front-a-deux-pas/releases/latest | jq -r '.tag_name | select(startswith("v"))')
        #     echo "FRONT_VERSION=${FRONT_VERSION#v}" >> $GITHUB_OUTPUT
        #     echo "BACK_VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT
        #   fi

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Set Docker permissions on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo usermod -aG docker $USER && newgrp docker'

      - name: Update secrets in environment file
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          STRIPE_TOKEN: ${{ secrets.STRIPE_TOKEN }}
        run: |
          ssh ${USER}@${HOST} "
            cd ~/app
            if [ -f src/environments/environment.prod.ts ]; then
              sed -i 's|MAPBOX_TOKEN_PLACEHOLDER|'\"${{ secrets.MAPBOX_TOKEN }}\"'|g' src/environments/environment.prod.ts
              sed -i 's|STRIPE_TOKEN_PLACEHOLDER|'\"${{ secrets.STRIPE_TOKEN }}\"'|g' src/environments/environment.prod.ts
              echo 'Environment file updated successfully'
            else
              echo 'Error: environment.prod.ts file not found'
              exit 1
            fi
          "

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          FRONT_VERSION: ${{ steps.versions.outputs.FRONT_VERSION }}
          BACK_VERSION: ${{ steps.versions.outputs.BACK_VERSION }}
        run: |
          scp docker-compose-test.yml ${USER}@${HOST}:~/app/
          ssh ${USER}@${HOST} '
            cd ~/app
            > .env
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env
            echo "FRONT_VERSION=${{ env.FRONT_VERSION }}" >> .env
            echo "BACK_VERSION=${{ env.BACK_VERSION }}" >> .env
            docker-compose -f docker-compose-test.yml config
            docker-compose -f docker-compose-test.yml pull
            # docker-compose -f docker-compose-test.yml up -d
          '
